import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnimatedName from "./components/animation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-black fixed w-full flex justify-center items-center px-8 h-20 text-2xl z-50">
          <div className="flex-initial">
            <div className="flex justify-end items-center relative">
              <div className="flex mr-4 items-center">
                <AnimatedName />
              </div>
            </div>
          </div>
        </nav>

        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
